---
title: "Untitled"
author: "N. Cheikh"
date: "5/7/2018"
output: html_document
---

```{r}
setwd("/Users/noracheikh/Desktop") #set the working directory
filename <- "testing.csv" #create label for filename
Testing <- read.csv(filename) #pull csv data frame into RStudio
filename <- "training.csv" #create label for filename
Training <- read.csv(filename) #pull csv data frame into RStudio
```

```{r}
testing1 <- Filter(function(x)!all(is.na(x) || is.null(x) || x == "" || x == 0), Testing) #remove columns that are empty or have NAs
testing1$problem_id <-NULL #remove the "problem_id" column from testing data
training1 <- Training[ , colSums(is.na(Training)) == 0]
testing1names <- colnames(testing1)
write.table(testing1names, file="testingnames.txt")
training1names <- colnames(training1)
write.table(training1names, file="training1names.txt")
#compare the column names
training2 <- training1[ -c(12:20,43:48,52:60,74:82) ] #manually remove the columns that are in training1 but not in testing1 and label new data frame training2
```

```{r}
#fix the levels of the factor variables for testing1 so that they match training2
levels.time <- levels(training2$cvtd_timestamp)
levels(testing1$cvtd_timestamp) <- levels.time
levels.window <- levels(training2$new_window)
levels(testing1$new_window) <- levels.window
```

```{r}
#save clean datasets as csv's
write.csv(training2, file="cleantraining.csv", row.names = FALSE)
write.csv(testing1, file="cleantesting.csv", row.names = FALSE)
```
